### ISSUE TITLE
Unifi does'nt existe in my home lab 

### ISSUE THREAD

**Issue by web-differently12** [christensenjairus/ClusterCreator#13]
hello 
i used Pfsense for my network and i haven't unifi api
variable "unifi_api_url" {
    default = "https://10.0.20.254/"
 my network is
vmbr0 is 192.168.1.1 with my box internet  
is vmbr1 with tag 200 10.0.20.1/24 with pfsense 
and i try to add this lab in this 
auto lanserver
iface lanserver inet manual
        ovs_type OVSIntPort
        ovs_bridge vmbr1
        ovs_options tag=200

Error: unable to determine API URL style: Get "https://10.0.20.254/": dial tcp 10.0.20.254:443: i/o timeout
│ 
│   with unifi_network.vlan["beta"],
│   on main.tf line 83, in resource "unifi_network" "vlan":
│   83: resource "unifi_network" "vlan" {
How i can confure it without Unifi. 
thanks you fir your help

**Comment by christensenjairus** [comment]
You can disable vlan creation in `clusters.tf`. 

`create_vlan = false`

This should disable all Unifi connections. However, you can still set the vlans for your VMs using `assign_vlan = true` so you can use your pfSense vlans.

Let me know if that fixes you issue and I'll update the docs to be more clear.

**Comment by web-differently12** [comment]
yes for network i think its necessary to have doc for exemple every node have three vlan ??..
 vlan_id                        = 600
        ipv4                           = {
          subnet_prefix                = "10.0.3"    this one 10.0.3.16 
          pod_cidr                     = "10.16.0.0/16" and this another vlan 
          svc_cidr                     = "10.17.0.0/16" and this 
          dns1                         = "10.0.3.3"
          dns2                         = "10.0.3.4"
        }
and all node 
for exemple my vlan is tag 200 with 10.0.20.1/24 dns and dhcp pfsense is 10.0.2O.254 
i should create three vlan for every node 10.0.3.1/24 and 10.16.0.0/16 and 10.17.0.0/16 and all for node Beta and gamma and alpha

**Comment by christensenjairus** [comment]
The `pod_cidr` and `svc_cidr` are internal to k8s and don't need to be provisioned by Unifi of pfSense. As long as your lan doesn't actually have the cidrs used by `pod_cidr` and `svc_cidr`, it should work.

**Comment by web-differently12** [comment]
yes thanks you i used now unifi with smal vm to have network without touche my network and i have probleme with this 


tofu apply 
local_file.cluster_config_json: Refreshing state... [id=f8c71889c8227cc5d93b4095657253d146fb066e]
unifi_network.vlan["gamma"]: Refreshing state... [id=673127d3ee7b0b3f0e0d45b8]
proxmox_virtual_environment_pool.operations_pool["gamma"]: Refreshing state... [id=GAMMA]

Planning failed. OpenTofu encountered an error while generating this plan.

╷
│ Error: error getting pool: received an HTTP 403 response - Reason: Permission check failed (/pool/GAMMA, Pool.Audit)
│ 
│   with proxmox_virtual_environment_pool.operations_pool["gamma"],
│   on main.tf line 121, in resource "proxmox_virtual_environment_pool" "operations_pool":
│  121: resource "proxmox_virtual_environment_pool" "operations_pool" {
privilege separate deactivate

**Comment by christensenjairus** [comment]
You'll need to add the Pool.Audit permission to you terraform user in Proxmox's console.

We're working on fixing the documentation regarding this so other users won't run into the same issue.

**Comment by web-differently12** [comment]
hello 
i revolved  Pool.Audit permission  i used this command 

pveum role add terraformProv -privs "Datastore.Allocate,Datastore.AllocateSpace,Datastore.AllocateTemplate,Datastore.Audit,Group.Allocate,Pool.Allocate,Pool.Audit,Sys.AccessNetwork,Sys.Audit,Sys.Console,Sys.Modify,VM.Allocate,VM.Audit,VM.Backup,VM.Clone,VM.Config.CDROM,VM.Config.CPU,VM.Config.Cloudinit,VM.Config.Disk,VM.Config.HWType,VM.Config.Memory,VM.Config.Network,VM.Config.Options,VM.Migrate,VM.Monitor,VM.PowerMgmt,VM.Snapshot SDN.Use"
and this 
pveum aclmod / -user terraform-prov@pve -role Administrator

now i have this error but i dont understand whats happened 
Error: error updating VM: the requested resource does not exist
│ 
│   with proxmox_virtual_environment_vm.node["beta-general-1"],
│   on main.tf line 139, in resource "proxmox_virtual_environment_vm" "node":
│  139: resource "proxmox_virtual_environment_vm" "node" {
│ 
╵
╷
│ Error: error updating VM: the requested resource does not exist
│ 
│   with proxmox_virtual_environment_vm.node["beta-apiserver-0"],
│   on main.tf line 139, in resource "proxmox_virtual_environment_vm" "node":
│  139: resource "proxmox_virtual_environment_vm" "node" {
│ 
╵
╷
│ Error: error updating VM: the requested resource does not exist
│ 
│   with proxmox_virtual_environment_vm.node["beta-general-0"],
│   on main.tf line 139, in resource "proxmox_virtual_environment_vm" "node":
│  139: resource "proxmox_virtual_environment_vm" "node" {

**Comment by web-differently12** [comment]
<img width="1339" alt="image" src="https://github.com/user-attachments/assets/7be57f7c-2680-4418-89d3-41c858638fab">

**Comment by web-differently12** [comment]
local_file.cluster_config_json: Destroying... [id=8fdfb30656aba6fa608f53e0aff6ccaf3a50349c]
local_file.cluster_config_json: Destruction complete after 0s
proxmox_virtual_environment_vm.node["beta-general-0"]: Destroying... [id=2130]
proxmox_virtual_environment_vm.node["beta-apiserver-0"]: Destroying... [id=2110]
proxmox_virtual_environment_vm.node["beta-general-1"]: Destroying... [id=2131]
proxmox_virtual_environment_vm.node["beta-apiserver-0"]: Destruction complete after 1s
proxmox_virtual_environment_vm.node["beta-general-1"]: Destruction complete after 1s
proxmox_virtual_environment_vm.node["beta-general-0"]: Destruction complete after 1s
proxmox_virtual_environment_pool.operations_pool["beta"]: Destroying... [id=BETA]
proxmox_virtual_environment_pool.operations_pool["beta"]: Destruction complete after 0s
unifi_network.vlan["beta"]: Destroying... [id=673226176e9bd271ecdda185]
unifi_network.vlan["beta"]: Destruction complete after 0s

Destroy complete! Resources: 6 destroyed.
mahjoubhamid@mahjoubs-MacBook-Pro ClusterCreator-main % tofu apply  

OpenTofu used the selected providers to generate the following execution plan. Resource actions are indicated
with the following symbols:
  + create

OpenTofu will perform the following actions:

  # local_file.cluster_config_json will be created
  + resource "local_file" "cluster_config_json" {
      + content              = jsonencode(
            {
              + cluster_id             = 2
              + cluster_name           = "beta"
              + kubeconfig_file_name   = "beta.yml"
              + local_path_provisioner = {
                  + local_path_provisioner_version = "0.0.29"
                }
              + max_pods_per_node      = 512
              + metrics_server         = {
                  + metrics_server_version = "0.7.2"
                }
              + networking             = {
                  + assign_vlan       = true
                  + bridge            = "vmbr1"
                  + cilium            = {
                      + cilium_version = "1.16.1"
                    }
                  + create_vlan       = true
                  + dns_search_domain = "lan"
                  + ipv4              = {
                      + dns1          = "10.0.2.3"
                      + dns2          = "10.0.2.4"
                      + pod_cidr      = "10.12.0.0/16"
                      + subnet_prefix = "10.0.2"
                      + svc_cidr      = "10.13.0.0/16"
                    }
                  + ipv6              = {
                      + dns1          = "2607:fa18::1"
                      + dns2          = "2607:fa18::2"
                      + dual_stack    = false
                      + enabled       = false
                      + pod_cidr      = "[replace-me]:200:244::/80"
                      + subnet_prefix = "[replace-me]:200"
                      + svc_cidr      = "[replace-me]:200:96::/112"
                    }
                  + kube_vip          = {
                      + kube_vip_version = "0.8.3"
                      + use_ipv6         = false
                      + vip              = "10.0.2.100"
                      + vip_hostname     = "beta-api-server"
                      + vip_interface    = "eth0"
                    }
                  + vlan_id           = 222
                  + vlan_name         = "BETA"
                }
              + node_classes           = {
                  + apiserver = {
                      + cores     = 4
                      + count     = 1
                      + cpu_type  = "x86-64-v2-AES"
                      + devices   = []
                      + disks     = [
                          + {
                              + aio_mode   = "io_uring"
                              + backup     = true
                              + cache_mode = "none"
                              + datastore  = "nvmes"
                              + index      = 0
                              + size       = 20
                            },
                        ]
                      + labels    = {
                          + nodeclass = "apiserver"
                        }
                      + machine   = "q35"
                      + memory    = 4096
                      + pve_nodes = [
                          + "pve",
                        ]
                      + sockets   = 1
                      + start_ip  = 110
                      + taints    = {}
                    }
                  + etcd      = {
                      + cores     = 2
                      + count     = 0
                      + cpu_type  = "x86-64-v2-AES"
                      + devices   = []
                      + disks     = [
                          + {
                              + aio_mode   = "io_uring"
                              + backup     = true
                              + cache_mode = "none"
                              + datastore  = "nvmes"
                              + index      = 0
                              + size       = 20
                            },
                        ]
                      + machine   = "q35"
                      + memory    = 2048
                      + pve_nodes = [
                          + "pve",
                        ]
                      + sockets   = 1
                      + start_ip  = 120
                    }
                  + general   = {
                      + cores     = 8
                      + count     = 2
                      + cpu_type  = "x86-64-v2-AES"
                      + devices   = []
                      + disks     = [
                          + {
                              + aio_mode   = "io_uring"
                              + backup     = true
                              + cache_mode = "none"
                              + datastore  = "nvmes"
                              + index      = 0
                              + size       = 20
                            },
                        ]
                      + labels    = {
                          + nodeclass = "general"
                        }
                      + machine   = "q35"
                      + memory    = 4096
                      + pve_nodes = [
                          + "pve",
                        ]
                      + sockets   = 1
                      + start_ip  = 130
                      + taints    = {}
                    }
                  + gpu       = {
                      + cores     = 2
                      + count     = 0
                      + cpu_type  = "host"
                      + devices   = [
                          + {
                              + index   = 0
                              + mapping = "my-full-gpu-passthrough"
                              + mdev    = ""
                              + rombar  = true
                              + type    = "pci"
                            },
                        ]
                      + disks     = [
                          + {
                              + aio_mode   = "io_uring"
                              + backup     = true
                              + cache_mode = "none"
                              + datastore  = "nvmes"
                              + index      = 0
                              + size       = 20
                            },
                        ]
                      + labels    = {
                          + nodeclass = "gpu"
                        }
                      + machine   = "q35"
                      + memory    = 2048
                      + pve_nodes = [
                          + "pve",
                        ]
                      + sockets   = 1
                      + start_ip  = 190
                      + taints    = {
                          + gpu = "true:NoSchedule"
                        }
                    }
                }
              + ssh                    = {
                  + ssh_home     = "/home/line6"
                  + ssh_key_type = "ssh-ed25519"
                  + ssh_user     = "line6"
                }
              + start_on_proxmox_boot  = false
            }
        )
      + content_base64sha256 = (known after apply)
      + content_base64sha512 = (known after apply)
      + content_md5          = (known after apply)
      + content_sha1         = (known after apply)
      + content_sha256       = (known after apply)
      + content_sha512       = (known after apply)
      + directory_permission = "0777"
      + file_permission      = "0777"
      + filename             = "ansible/tmp/beta/cluster_config.json"
      + id                   = (known after apply)
    }

  # proxmox_virtual_environment_pool.operations_pool["beta"] will be created
  + resource "proxmox_virtual_environment_pool" "operations_pool" {
      + comment = "Managed by Terraform"
      + id      = (known after apply)
      + members = (known after apply)
      + pool_id = "BETA"
    }

  # proxmox_virtual_environment_vm.node["beta-apiserver-0"] will be created
  + resource "proxmox_virtual_environment_vm" "node" {
      + acpi                    = true
      + bios                    = "seabios"
      + description             = "Managed by Terraform"
      + id                      = (known after apply)
      + ipv4_addresses          = (known after apply)
      + ipv6_addresses          = (known after apply)
      + keyboard_layout         = "en-us"
      + mac_addresses           = (known after apply)
      + machine                 = "q35"
      + migrate                 = true
      + name                    = "beta-apiserver-0"
      + network_interface_names = (known after apply)
      + node_name               = "pve"
      + on_boot                 = false
      + pool_id                 = "BETA"
      + protection              = false
      + reboot                  = false
      + scsi_hardware           = "virtio-scsi-pci"
      + started                 = true
      + stop_on_destroy         = false
      + tablet_device           = true
      + tags                    = [
          + "k8s",
          + "beta",
          + "apiserver",
        ]
      + template                = false
      + timeout_clone           = 1800
      + timeout_create          = 1800
      + timeout_migrate         = 1800
      + timeout_move_disk       = 1800
      + timeout_reboot          = 1800
      + timeout_shutdown_vm     = 1800
      + timeout_start_vm        = 1800
      + timeout_stop_vm         = 300
      + vm_id                   = 2110

      + agent {
          + enabled = true
          + timeout = "15m"
          + trim    = true
          + type    = "virtio"
        }

      + clone {
          + full      = true
          + node_name = "pve"
          + retries   = 25
          + vm_id     = 9000
        }

      + cpu {
          + cores      = 4
          + flags      = []
          + hotplugged = 0
          + limit      = 0
          + numa       = true
          + sockets    = 1
          + type       = "x86-64-v2-AES"
          + units      = 1024
        }

      + disk {
          + aio               = "io_uring"
          + backup            = true
          + cache             = "none"
          + datastore_id      = "nvmes"
          + discard           = "ignore"
          + file_format       = "raw"
          + interface         = "virtio0"
          + iothread          = true
          + path_in_datastore = (known after apply)
          + replicate         = true
          + size              = 20
          + ssd               = false
        }

      + initialization {
          + datastore_id = "nvmes"
          + interface    = "ide2"
          + upgrade      = (known after apply)

          + dns {
              + domain  = "lan"
              + servers = [
                  + "10.0.2.3",
                  + "10.0.2.4",
                  + "10.0.2.1",
                ]
            }

          + ip_config {
              + ipv4 {
                  + address = "10.0.2.110/24"
                  + gateway = "10.0.2.1"
                }
            }

          + user_account {
              + keys     = [
                  + "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIM9YAIXm3cQ0Ql3JqLlnG9LkxfgeIfNxam3NU2v7i9In hamid.mahjoub@student.centralia.edu",
                ]
              + password = (sensitive value)
              + username = "youssef"
            }
        }

      + memory {
          + dedicated      = 4096
          + floating       = 0
          + keep_hugepages = false
          + shared         = 0
        }

      + network_device {
          + bridge      = "vmbr1"
          + enabled     = true
          + firewall    = false
          + mac_address = (known after apply)
          + model       = "virtio"
          + mtu         = 0
          + queues      = 0
          + rate_limit  = 0
          + vlan_id     = 222
        }

      + vga {
          + memory = 16
          + type   = "serial0"
        }
    }

  # proxmox_virtual_environment_vm.node["beta-general-0"] will be created
  + resource "proxmox_virtual_environment_vm" "node" {
      + acpi                    = true
      + bios                    = "seabios"
      + description             = "Managed by Terraform"
      + id                      = (known after apply)
      + ipv4_addresses          = (known after apply)
      + ipv6_addresses          = (known after apply)
      + keyboard_layout         = "en-us"
      + mac_addresses           = (known after apply)
      + machine                 = "q35"
      + migrate                 = true
      + name                    = "beta-general-0"
      + network_interface_names = (known after apply)
      + node_name               = "pve"
      + on_boot                 = false
      + pool_id                 = "BETA"
      + protection              = false
      + reboot                  = false
      + scsi_hardware           = "virtio-scsi-pci"
      + started                 = true
      + stop_on_destroy         = false
      + tablet_device           = true
      + tags                    = [
          + "k8s",
          + "beta",
          + "general",
        ]
      + template                = false
      + timeout_clone           = 1800
      + timeout_create          = 1800
      + timeout_migrate         = 1800
      + timeout_move_disk       = 1800
      + timeout_reboot          = 1800
      + timeout_shutdown_vm     = 1800
      + timeout_start_vm        = 1800
      + timeout_stop_vm         = 300
      + vm_id                   = 2130

      + agent {
          + enabled = true
          + timeout = "15m"
          + trim    = true
          + type    = "virtio"
        }

      + clone {
          + full      = true
          + node_name = "pve"
          + retries   = 25
          + vm_id     = 9000
        }

      + cpu {
          + cores      = 8
          + flags      = []
          + hotplugged = 0
          + limit      = 0
          + numa       = true
          + sockets    = 1
          + type       = "x86-64-v2-AES"
          + units      = 1024
        }

      + disk {
          + aio               = "io_uring"
          + backup            = true
          + cache             = "none"
          + datastore_id      = "nvmes"
          + discard           = "ignore"
          + file_format       = "raw"
          + interface         = "virtio0"
          + iothread          = true
          + path_in_datastore = (known after apply)
          + replicate         = true
          + size              = 20
          + ssd               = false
        }

      + initialization {
          + datastore_id = "nvmes"
          + interface    = "ide2"
          + upgrade      = (known after apply)

          + dns {
              + domain  = "lan"
              + servers = [
                  + "10.0.2.3",
                  + "10.0.2.4",
                  + "10.0.2.1",
                ]
            }

          + ip_config {
              + ipv4 {
                  + address = "10.0.2.130/24"
                  + gateway = "10.0.2.1"
                }
            }

          + user_account {
              + keys     = [
                  + "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIM9YAIXm3cQ0Ql3JqLlnG9LkxfgeIfNxam3NU2v7i9In hamid.mahjoub@student.centralia.edu",
                ]
              + password = (sensitive value)
              + username = "youssef"
            }
        }

      + memory {
          + dedicated      = 4096
          + floating       = 0
          + keep_hugepages = false
          + shared         = 0
        }

      + network_device {
          + bridge      = "vmbr1"
          + enabled     = true
          + firewall    = false
          + mac_address = (known after apply)
          + model       = "virtio"
          + mtu         = 0
          + queues      = 0
          + rate_limit  = 0
          + vlan_id     = 222
        }

      + vga {
          + memory = 16
          + type   = "serial0"
        }
    }

  # proxmox_virtual_environment_vm.node["beta-general-1"] will be created
  + resource "proxmox_virtual_environment_vm" "node" {
      + acpi                    = true
      + bios                    = "seabios"
      + description             = "Managed by Terraform"
      + id                      = (known after apply)
      + ipv4_addresses          = (known after apply)
      + ipv6_addresses          = (known after apply)
      + keyboard_layout         = "en-us"
      + mac_addresses           = (known after apply)
      + machine                 = "q35"
      + migrate                 = true
      + name                    = "beta-general-1"
      + network_interface_names = (known after apply)
      + node_name               = "pve"
      + on_boot                 = false
      + pool_id                 = "BETA"
      + protection              = false
      + reboot                  = false
      + scsi_hardware           = "virtio-scsi-pci"
      + started                 = true
      + stop_on_destroy         = false
      + tablet_device           = true
      + tags                    = [
          + "k8s",
          + "beta",
          + "general",
        ]
      + template                = false
      + timeout_clone           = 1800
      + timeout_create          = 1800
      + timeout_migrate         = 1800
      + timeout_move_disk       = 1800
      + timeout_reboot          = 1800
      + timeout_shutdown_vm     = 1800
      + timeout_start_vm        = 1800
      + timeout_stop_vm         = 300
      + vm_id                   = 2131

      + agent {
          + enabled = true
          + timeout = "15m"
          + trim    = true
          + type    = "virtio"
        }

      + clone {
          + full      = true
          + node_name = "pve"
          + retries   = 25
          + vm_id     = 9000
        }

      + cpu {
          + cores      = 8
          + flags      = []
          + hotplugged = 0
          + limit      = 0
          + numa       = true
          + sockets    = 1
          + type       = "x86-64-v2-AES"
          + units      = 1024
        }

      + disk {
          + aio               = "io_uring"
          + backup            = true
          + cache             = "none"
          + datastore_id      = "nvmes"
          + discard           = "ignore"
          + file_format       = "raw"
          + interface         = "virtio0"
          + iothread          = true
          + path_in_datastore = (known after apply)
          + replicate         = true
          + size              = 20
          + ssd               = false
        }

      + initialization {
          + datastore_id = "nvmes"
          + interface    = "ide2"
          + upgrade      = (known after apply)

          + dns {
              + domain  = "lan"
              + servers = [
                  + "10.0.2.3",
                  + "10.0.2.4",
                  + "10.0.2.1",
                ]
            }

          + ip_config {
              + ipv4 {
                  + address = "10.0.2.131/24"
                  + gateway = "10.0.2.1"
                }
            }

          + user_account {
              + keys     = [
                  + "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIM9YAIXm3cQ0Ql3JqLlnG9LkxfgeIfNxam3NU2v7i9In hamid.mahjoub@student.centralia.edu",
                ]
              + password = (sensitive value)
              + username = "youssef"
            }
        }

      + memory {
          + dedicated      = 4096
          + floating       = 0
          + keep_hugepages = false
          + shared         = 0
        }

      + network_device {
          + bridge      = "vmbr1"
          + enabled     = true
          + firewall    = false
          + mac_address = (known after apply)
          + model       = "virtio"
          + mtu         = 0
          + queues      = 0
          + rate_limit  = 0
          + vlan_id     = 222
        }

      + vga {
          + memory = 16
          + type   = "serial0"
        }
    }

  # unifi_network.vlan["beta"] will be created
  + resource "unifi_network" "vlan" {
      + dhcp_dns                     = [
          + "10.0.2.3",
          + "10.0.2.4",
        ]
      + dhcp_enabled                 = true
      + dhcp_lease                   = 86400
      + dhcp_start                   = "10.0.2.10"
      + dhcp_stop                    = "10.0.2.99"
      + dhcp_v6_dns                  = []
      + dhcp_v6_dns_auto             = false
      + dhcp_v6_enabled              = true
      + dhcp_v6_lease                = 86400
      + dhcp_v6_start                = "::10"
      + dhcp_v6_stop                 = "::99"
      + id                           = (known after apply)
      + igmp_snooping                = false
      + internet_access_enabled      = true
      + intra_network_access_enabled = true
      + ipv6_interface_type          = "none"
      + ipv6_ra_enable               = true
      + ipv6_ra_preferred_lifetime   = 14400
      + ipv6_ra_priority             = "high"
      + ipv6_ra_valid_lifetime       = 86400
      + multicast_dns                = false
      + name                         = "BETA"
      + network_group                = "LAN"
      + purpose                      = "corporate"
      + site                         = (known after apply)
      + subnet                       = "10.0.2.0/24"
      + vlan_id                      = 222
      + wan_egress_qos               = 0
    }

Plan: 6 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + filtered_nodes = [
      + {
          + bridge            = "vmbr1"
          + cluster_name      = "beta"
          + cores             = 4
          + cpu_type          = "x86-64-v2-AES"
          + create_vlan       = true
          + devices           = []
          + disks             = [
              + {
                  + aio_mode   = "io_uring"
                  + backup     = true
                  + cache_mode = "none"
                  + datastore  = "nvmes"
                  + index      = 0
                  + size       = 20
                },
            ]
          + dns_search_domain = "lan"
          + index             = 0
          + ipv4              = {
              + dns1    = "10.0.2.3"
              + dns2    = "10.0.2.4"
              + gateway = "10.0.2.1"
              + vm_ip   = "10.0.2.110"
            }
          + ipv6              = {
              + dns1       = null
              + dns2       = null
              + dual_stack = false
              + enabled    = false
              + gateway    = null
              + vm_ip      = null
            }
          + machine           = "q35"
          + memory            = 4096
          + node_class        = "apiserver"
          + on_boot           = false
          + pve_nodes         = [
              + "pve",
            ]
          + sockets           = 1
          + vlan_id           = 222
          + vlan_name         = "BETA"
          + vm_id             = 2110
        },
      + {
          + bridge            = "vmbr1"
          + cluster_name      = "beta"
          + cores             = 8
          + cpu_type          = "x86-64-v2-AES"
          + create_vlan       = true
          + devices           = []
          + disks             = [
              + {
                  + aio_mode   = "io_uring"
                  + backup     = true
                  + cache_mode = "none"
                  + datastore  = "nvmes"
                  + index      = 0
                  + size       = 20
                },
            ]
          + dns_search_domain = "lan"
          + index             = 0
          + ipv4              = {
              + dns1    = "10.0.2.3"
              + dns2    = "10.0.2.4"
              + gateway = "10.0.2.1"
              + vm_ip   = "10.0.2.130"
            }
          + ipv6              = {
              + dns1       = null
              + dns2       = null
              + dual_stack = false
              + enabled    = false
              + gateway    = null
              + vm_ip      = null
            }
          + machine           = "q35"
          + memory            = 4096
          + node_class        = "general"
          + on_boot           = false
          + pve_nodes         = [
              + "pve",
            ]
          + sockets           = 1
          + vlan_id           = 222
          + vlan_name         = "BETA"
          + vm_id             = 2130
        },
      + {
          + bridge            = "vmbr1"
          + cluster_name      = "beta"
          + cores             = 8
          + cpu_type          = "x86-64-v2-AES"
          + create_vlan       = true
          + devices           = []
          + disks             = [
              + {
                  + aio_mode   = "io_uring"
                  + backup     = true
                  + cache_mode = "none"
                  + datastore  = "nvmes"
                  + index      = 0
                  + size       = 20
                },
            ]
          + dns_search_domain = "lan"
          + index             = 1
          + ipv4              = {
              + dns1    = "10.0.2.3"
              + dns2    = "10.0.2.4"
              + gateway = "10.0.2.1"
              + vm_ip   = "10.0.2.131"
            }
          + ipv6              = {
              + dns1       = null
              + dns2       = null
              + dual_stack = false
              + enabled    = false
              + gateway    = null
              + vm_ip      = null
            }
          + machine           = "q35"
          + memory            = 4096
          + node_class        = "general"
          + on_boot           = false
          + pve_nodes         = [
              + "pve",
            ]
          + sockets           = 1
          + vlan_id           = 222
          + vlan_name         = "BETA"
          + vm_id             = 2131
        },
    ]

Do you want to perform these actions in workspace "beta"?
  OpenTofu will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

unifi_network.vlan["beta"]: Creating...
local_file.cluster_config_json: Creating...
local_file.cluster_config_json: Creation complete after 0s [id=8fdfb30656aba6fa608f53e0aff6ccaf3a50349c]
unifi_network.vlan["beta"]: Creation complete after 0s [id=673226976e9bd271ecdda18c]
proxmox_virtual_environment_pool.operations_pool["beta"]: Creating...
proxmox_virtual_environment_pool.operations_pool["beta"]: Creation complete after 0s [id=BETA]
proxmox_virtual_environment_vm.node["beta-general-1"]: Creating...
proxmox_virtual_environment_vm.node["beta-general-0"]: Creating...
proxmox_virtual_environment_vm.node["beta-apiserver-0"]: Creating...
╷
│ Error: error updating VM: the requested resource does not exist
│ 
│   with proxmox_virtual_environment_vm.node["beta-general-1"],
│   on main.tf line 143, in resource "proxmox_virtual_environment_vm" "node":
│  143: resource "proxmox_virtual_environment_vm" "node" {
│ 
╵
╷
│ Error: error updating VM: the requested resource does not exist
│ 
│   with proxmox_virtual_environment_vm.node["beta-apiserver-0"],
│   on main.tf line 143, in resource "proxmox_virtual_environment_vm" "node":
│  143: resource "proxmox_virtual_environment_vm" "node" {
│ 
╵
╷
│ Error: error updating VM: the requested resource does not exist
│ 
│   with proxmox_virtual_environment_vm.node["beta-general-0"],
│   on main.tf line 143, in resource "proxmox_virtual_environment_vm" "node":
│  143: resource "proxmox_virtual_environment_vm" "node" {
│

**Comment by christensenjairus** [comment]
I'd revisit creating the terraform user and token. Don't forget to generate the token with privilege separation disabled

`sudo pveum user token add terraform@pve provider --privsep=0`

**Comment by web-differently12** [comment]
yes i have create new user but i have this probleme, vm not started 

 fi_network.vlan["beta"]: Creation complete after 0s [id=673247ca791dee5107c9ced4]
proxmox_virtual_environment_pool.operations_pool["beta"]: Creating...
proxmox_virtual_environment_pool.operations_pool["beta"]: Creation complete after 0s [id=BETA]
proxmox_virtual_environment_vm.node["beta-general-0"]: Creating...
proxmox_virtual_environment_vm.node["beta-apiserver-0"]: Creating...
proxmox_virtual_environment_vm.node["beta-general-1"]: Creating...
╷
│ Error: error updating VM: the requested resource does not exist
│ 
│   with proxmox_virtual_environment_vm.node["beta-general-1"],
│   on main.tf line 143, in resource "proxmox_virtual_environment_vm" "node":
│  143: resource "proxmox_virtual_environment_vm" "node" {
│

**Comment by christensenjairus** [comment]
Awesome! Let me know if you need anything else.
